# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

deafault_twitter: &deafault_twitter
  twitter_api_key: 'tP3ac4AcSPfpwetCyvMHWsku8'
  twitter_api_secret: 'J1ZtlARn95N5s1x56BPTeGIjrgfzbXYlYtizTztwRV2dDv4oI6'

default_facebook: &default_facebook
  facebook_api_key: '1178070272277957'
  facebook_api_secret: '843f0c4b6b3af92add0d371497872a8d'


development:
  secret_key_base: 18e2d61d7fe208976ac3b1ddb262847d64c0ef9bfedd6fdea17783a3aca596f9f491149054f6f53f587bd960890cc1eaaa7dfb8be0d8a37d4d1137c6985bb4cc
  <<: *default_facebook
  <<: *deafault_twitter
test:
  secret_key_base: 7f424bff11223ee902f2d65a64e8b5261374797f90c759629d0283eba98c7fe063f775fe9bb7e0f309c99b4c18c0668674d3f04ff1cb5cdcc275c2372b25fc7a
  <<: *default_facebook
  <<: *deafault_twitter
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"]%>
  twitter_api_secret: <%= ENV["TEITTER_CONSUMER_SECRET"]%>
  facebook_api_key: <%= ENV["FACEBOOK_API_KEY"] %>
  facebook_api_secret: <%= ENV["FACEBOOK_API_SECRET"] %>